version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - "5000:5000"
    volumes:
      - ./services/backend:/app/services/backend
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"